version: '3.8'

services:
  web:
    build: .
    ports:
      - "${FLASK_PORT}:5000"  # Используем переменную из .env
    environment:
      - DATABASE_URL=${DATABASE_URL}  # Используем переменную из .env
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  alembic:
    build: .
    command: alembic upgrade head  # Выполнение миграций при запуске контейнера
    environment:
      - DATABASE_URL=${DATABASE_URL}  # Используем переменную из .env
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:
