name: Deploy to Server

on:
  push:
    branches:
      - main  # Укажите вашу основную ветку

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t flask-schedule-app-backend:latest .
          docker tag flask-schedule-app-backend:latest vesta118/flask-schedule-app-backend:latest
          docker push vesta118/flask-schedule-app-backend:latest

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Restart Docker containers
        run: ssh -t ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "cd /home/viktoria/apps/flask-schedule-app-backend && docker-compose down && docker-compose up -d"
